# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

In [1]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.9.7


### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

### Exercício 1

In [3]:
# Importando o NumPy
import numpy as np

In [15]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?

a = np.arange(1000000)
l = list(range(1000000))

%time for _ in range(10): a2 = a * 2
%time for _ in range(10): l2 = [x * 2 for x in l]

Wall time: 22 ms
Wall time: 1.05 s


### Exercício 2

In [20]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0
a = np.arange(10)
a[5:8] = 0
print(a)

[0 1 2 3 4 0 0 0 8 9]


### Exercício 3

In [27]:
# Crie um array de 3 dimensões e imprima a dimensão 1
array = np.array([[[1, 2, 5], [3, 4, 7]], [[5, 6, 6], [7, 8, 3]]])
print(array)

array[0]

[[[1 2 5]
  [3 4 7]]

 [[5 6 6]
  [7 8 3]]]


array([[1, 2, 5],
       [3, 4, 7]])

### Exercício 4

In [35]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas
a_2d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(a_2d_array)

a_2d_array[2]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


array([[1, 2, 3]])

In [40]:
# Imprima os elementos da terceira linha da matriz
a_2d_array[2]

array([7, 8, 9])

In [52]:
# Imprima todos os elementos da primeira e segunda linhas
a_2d_array[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
# e segunda 
a_2d_array[:,1]

array([ 2,  5,  8, 11])

In [56]:
# e terceira colunas
a_2d_array[:,2]

array([ 3,  6,  9, 12])

### Exercício 5

In [58]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [59]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### Exercício 6

In [69]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [70]:
for x, y, z in zip( xarr, yarr, cond):
    print(x,y,z)

1.1 2.1 True
1.2 2.2 False
1.3 2.3 True
1.4 2.4 True
1.5 2.5 False


### Exercício 7

In [75]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B
a = np.arange(10)
a
np.save('array_a',a)

In [76]:
b = np.load('array_a.npy')
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Exercício 8

In [78]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])
myset = set(obj)
print(myset)


{'b', 'd', 'c', 'a'}


### Exercício 9

In [79]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

<Response [200]>

In [80]:
data = resp.json()
data[0]['title']

'ENH: Enumeration grouping'

In [82]:
issues = pd.DataFrame(data, columns = ['number', 'title', 'labels', 'state'])
issues

number                                              title  \
0    46147                          ENH: Enumeration grouping   
1    46146  BUG: segfault when using read_csv and repeated...   
2    46145  BUG: dataframe/series.isna().sum() overcounts ...   
3    46144    CI/TST: Flaky test `test_union_different_types`   
4    46143               CI: Merge datamanager job into posix   
5    46142         REF: combine masked_cummin_max, cummin_max   
6    46141                  [WIP] DataFrame exchange protocol   
7    46140         Bug fix extension array with 2d datetime64   
8    46139                                       close #25399   
9    46138  BUG: NotImplementedError: Cannot apply ufunc <...   
10   46137                   CLN: Remove Categorical.itemsize   
11   46135  BUG: rolling with axis=1, win_type=, and cente...   
12   46134               DEPR: non-keyword args in EA.argsort   
13   46133                              TYP: groupby, sorting   
14   46132  BUG: rolling aggregate() with a list of functi...   
15   46131  REF: remove no-longer-needed _validate_numeric...   
16   46129     BUG: df.plot(kind='barh') does not show xlabel   
17   46128   Remove some dead code in core/arrays/interval.py   
18   46126  ENH: Conversion function errors kwarg callback...   
19   46124                           DOC: Improve options.rst   
20   46122  ENH: Add option to specify table captions to b...   
21   46121                                      TYP: assorted   
22   46119           REF: isinstance(x, int) -> is_integer(x)   
23   46118     CI: Align MacOS dependencies with other builds   
24   46116  [Work in progress] perf improvements for strftime   
25   46114  DOC: Add note for tail/head when n is larger t...   
26   46112  BUG: DataFrame.to_json does not take into acco...   
27   46111  BUG: cannot use registered float16 extension d...   
28   46110              BUG: PandasArray._quantile when empty   
29   46109           PERF: avoid unnecessary copies factorize   

                                               labels state  
0   [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
1   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
2   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
3   [{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2OD...  open  
4   [{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...  open  
5   [{'id': 127681, 'node_id': 'MDU6TGFiZWwxMjc2OD...  open  
6                                                  []  open  
7                                                  []  open  
8                                                  []  open  
9   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
10                                                 []  open  
11  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
12  [{'id': 87485152, 'node_id': 'MDU6TGFiZWw4NzQ4...  open  
13                                                 []  open  
14  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
15  [{'id': 127681, 'node_id': 'MDU6TGFiZWwxMjc2OD...  open  
16  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
17  [{'id': 150096370, 'node_id': 'MDU6TGFiZWwxNTA...  open  
18  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
19  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
20  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
21                                                 []  open  
22  [{'id': 127681, 'node_id': 'MDU6TGFiZWwxMjc2OD...  open  
23  [{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...  open  
24                                                 []  open  
25                                                 []  open  
26  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
27  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
28                                                 []  open  
29  [{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1M...  open

### Exercício 10

In [1]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas
import sqlite3
import pandas as pd

query = """
CREATE TABLE TESTE
(nome VARCHAR(20), 
 cpf VARCHAR(14),
 salario Numeric(10,2)
);"""
con = sqlite3.connect('dsa_joanes.db')
con.execute(query)
con.commit()

In [2]:
data = [('Joanes', '44422244499', 2.250),
        ('Carlos', '55522244499', 1.500),
        ('Edjane', '55522244488', 6.500)]
stmt = "INSERT INTO TESTE VALUES(?, ?, ?)"
con.executemany(stmt, data)
con.commit()

In [3]:
cursor = con.execute('select * from teste')
rows = cursor.fetchall()
rows

[('Joanes', '44422244499', 2.25),
 ('Carlos', '55522244499', 1.5),
 ('Edjane', '55522244488', 6.5)]

In [4]:
cursor.description
pd.DataFrame(rows, columns=[x[0] for x in cursor.description])

nome          cpf  salario
0  Joanes  44422244499     2.25
1  Carlos  55522244499     1.50
2  Edjane  55522244488     6.50

# Fim


### Obrigado

### Visite o Blog da Data Science Academy - <a href="http://blog.dsacademy.com.br">Blog DSA</a>
